[WIP]DB設計
98hira/chat-space pull request #1
Opened 2019-02-18 12:16 UTC by 98hira

# WHAT
DB設計をREADME.mdに記載。

# WHY
サービスに必須の機能であるため。

2019-02-18 12:36 UTC, ghost requested changes

2019-02-18 12:36 UTC, hiroki5123 commented on README.md
> +
アソシエーションが一つ足りないので見直してみましょう

2019-02-18 12:36 UTC, hiroki5123 commented on README.md
> +
こちらもアソシエーションが一つ足りないので見直してみましょう

2019-02-18 12:36 UTC, hiroki5123 commented on README.md
> +| image  | binary    |                                |
こちらはtextで大丈夫です

2019-02-18 12:36 UTC, hiroki5123 commented on README.md
> +| GroupName | text | null: false |
nameでいいと思います

2019-02-18 12:42 UTC, 98hira commented on README.md
> +| GroupName | text | null: false |
承知しました。

2019-02-19 02:05 UTC, hirozak commented on README.md
> +| nickname | text   | null: false |
stringですね

2019-02-19 02:06 UTC, hirozak commented
https://github.com/98hira/chat-space/pull/1#discussion_r257677471
修正されていないです

2019-02-19 09:04 UTC, 98hira commented on README.md
> +| image  | binary    |                                |
imageカラムはのTypeはbinariでなくtextの方がいいということでしょうか？

その場合、画像ファイルの実体はどこで管理するのでしょうか？
後、imageカラムが画像のファイル名だけを保存する場合、stringでなくtextの理由はなんでしょうか？

2019-02-19 09:06 UTC, 98hira commented on README.md
> +
修正内容が不明なため、関連する指摘であると思われる#1 (comment)に疑問点をまとめます。

2019-02-19 09:21 UTC, 98hira commented on README.md
> +
こちらを参考にすると、
https://github.com/hiroki5123/ChatApp

以下を追加すればいいと思われるのですが、理由が不明なため教えていただけないでしょうか？
`has_many :users, through: :groups_users `

2019-02-19 09:22 UTC, 98hira commented on README.md
> +
こちらを参考にすると、
https://github.com/hiroki5123/ChatApp

以下を追加すればいいと思われるのですが、理由が不明なため教えていただけないでしょうか？
`has_many :users, through: :groups_users `

2019-02-20 02:50 UTC, 98hira commented
> [#1 (comment)](https://github.com/98hira/chat-space/pull/1#discussion_r257677471)
> 修正されていないです
修正内容が理解できないため、まだコミットしていません。

2019-02-20 03:15 UTC, TOMARUMARU reviewed
chatspaceは多対多のアソシエーションになります。調べていただいて修正をお願いします

2019-02-20 04:14 UTC, 98hira reviewed
> chatspaceは多対多のアソシエーションになります。調べていただいて修正をお願いします

修正しました。

2019-02-20 04:14 UTC, 98hira commented on README.md
> +*devise
**質問**
チャットスペースのUI上ではnicknameのみで個人を識別しているようなので、nicknameカラムへ一意制約をつける必要があると思うのですがいかがでしょうか？
因みにdeviseを使って生成されるテーブルのため、デフォルトのemailカラムに関しては一意制約が付いているのですが、明示的にするためこちらにも一位制約の記述を追加すべきだと考えます。

2019-02-20 05:02 UTC, TOMARUMARU commented on README.md
> +*devise
> チャットスペースのUI上ではnicknameのみで個人を識別しているようなので、nicknameカラムへ一意制約をつける必要があると思うのですがいかがでしょうか？

おっしゃる通りですね。一意制約をかける必要があります。

> 因みにdeviseを使って生成されるテーブルのため、デフォルトのemailカラムに関しては一意制約が付いているのですが、明示的にするためこちらにも一位制約の記述を追加すべきだと考えます。

email, passwordに関してはdeviseのモデルを作成する際に自動でカラムが生成されるので、特に気にしていただかなくて大丈夫です。

2019-02-20 05:03 UTC, TOMARUMARU commented on README.md
> +| nickname | string | null: false |
nicknameで検索をかける機能をつけるのでindexも貼りましょう

2019-02-20 07:09 UTC, 98hira commented
https://github.com/98hira/chat-space/pull/1#discussion_r257943810
こちらについて、回答頂けないでしょうか。

2019-02-20 07:10 UTC, 98hira commented on README.md
> +| nickname | string | null: false |
以下コミットにて修正しました。
[cef05a1](https://github.com/98hira/chat-space/commit/cef05a1ef3d1cd490c89e3bcab9cbc0d3ca6b99e)

2019-02-20 07:40 UTC, kuroko918 commented on README.md
> +
こちらの記述をすると、group.usersなどと、記述し、groupからuserを取ってくることができます！

2019-02-20 07:42 UTC, kuroko918 commented
> [#1 (comment)](https://github.com/98hira/chat-space/pull/1#discussion_r257943810)
> こちらについて、回答頂けないでしょうか。

こちら回答させていただきました。

他の部分は問題ないかと思います。
マージして次に進んでください！

2019-02-20 07:53 UTC, 98hira commented
> > [#1 (comment)](https://github.com/98hira/chat-space/pull/1#discussion_r257943810)
> > こちらについて、回答頂けないでしょうか。
> 
> こちら回答させていただきました。
> 
> 他の部分は問題ないかと思います。
> マージして次に進んでください！

↓こちらではなく
> https://github.com/98hira/chat-space/pull/1#discussion_r257950541

↓こちらに回答いただきたかったのですが。。。
> [#1 (comment)](https://github.com/98hira/chat-space/pull/1#discussion_r257943810)
>imageカラムのTypeはbinariでなくtextの方がいいということでしょうか？
>その場合、画像ファイルの実体はどこで管理するのでしょうか？
>後、imageカラムが画像のファイル名だけを保存する場合、stringでなくtextの理由はなんでしょうか？>ファイル名が255文字以上になるとは到底思えないのですが。

2019-02-20 08:13 UTC, kuroko918 commented
こちらの不備で失礼致しました。引用していただけると大変助かります。
こちらですが、imageのデータをDBに入れるのではなく、S3というところにimageのデータを保存して、そこのURLをDBで保存する為、textとなるという次第です。

2019-02-20 08:16 UTC, 98hira commented on README.md
> +| image  | binary    |                                |
以下で回答いただいた。
> https://github.com/98hira/chat-space/pull/1#issuecomment-465470019
>imageのデータをDBに入れるのではなく、S3というところにimageのデータを保存して、そこのURLをDBで保存する為、textとなるという次第です。

2019-02-20 08:58 UTC, merged